# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature_371 ]
  pull_request:
    branches: [ feature_371 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release: [R2021a, R2021b]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.release }}

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results_${{ matrix.release }}.xml
          test-results-pdf: test-results/results_${{ matrix.release }}.pdf
          source-folder: functions
          code-coverage-cobertura: coverage_${{ matrix.release }}.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage_${{ matrix.release }}.xml
          flags: ${{ matrix.release }}
